services:
  - type: web
    name: mama-konditorskaya
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NEXT_PUBLIC_TELEGRAM_BOT_TOKEN
        sync: false
      - key: NEXT_PUBLIC_TELEGRAM_CHAT_ID
        sync: false
    autoDeploy: true
