services:
  - type: web
    name: mama-konditorskaya
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://mama-konditorskaya.onrender.com
    autoDeploy: true
